import avatar from "../Assets/profilePicAvatar.png";

const DatatableSource = [
  {
    id: 1,
    name: "Martin Nwatu",
    email: "martin@gmail.com",
    gender: "Male",
    username: "martinmatics",
    avatar: avatar,
  },
  {
    id: 2,
    name: "John Doe",
    email: "john.doe@example.com",
    gender: "Male",
    username: "johndoe",
    avatar: avatar,
  },
  {
    id: 3,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 4,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 5,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 6,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 7,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 8,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 9,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 10,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 11,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 12,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 13,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 14,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 15,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 16,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 17,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 18,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 19,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 20,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 21,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 22,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 23,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 24,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 25,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 26,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 27,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 28,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 29,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 30,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 31,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 32,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 33,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 34,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 35,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 36,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 37,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 38,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 39,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 40,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 41,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 42,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 43,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 44,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 45,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 46,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 47,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 48,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 49,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 50,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 51,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 52,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 53,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 54,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 55,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 56,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 57,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 58,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 59,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 60,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 61,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 62,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 63,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 64,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 65,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 66,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
  {
    id: 67,
    name: "Martin Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    username: "janesmith",
    avatar: avatar,
  },
];

export default DatatableSource;
